config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :inventories
  resources :products
	resources :orders
	resources :addresses 
	resources :line_items, shallow: true do
   		collection { post :import }
   end

	devise_for :users, :controllers => { registrations: 'users/registrations' }
	
	root "pages#home"
	get "faq" => "pages#faq"
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	belongs_to :address
	has_many :line_items, inverse_of: :order
	accepts_nested_attributes_for :line_items

	validates :spreadsheet_link, presence: true
	validates :date, presence: true 

	BIA_ENTITIES = [['Under The Lights', 'UTL'], ['Coast to Coast', 'CTC'], ['Speed LAX', 'LAX']]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  load_and_authorize_resource :only => [:new, :edit, :destroy]
   
  before_action :require_login
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def require_login
    unless current_user
      redirect_to new_user_session_path
    end
  end

  def index
    @orders = Order.all
  end

  def show
    @line_items = @order.line_items.group(:team, :shirtcolor, :inkcolor).sum(:shirt_quantity)
    @message = Message.new
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "pdf_name"
      end
    end
  end

  def new
    @order = current_user.orders.build
  end

  def edit
  end

  def create
    @order = current_user.orders.build(order_params)
    if @order.save
      # Sends email to user when order is created. I may want to change this later to after line_items are created.
      OrderMailer.new_order(@order).deliver
      redirect_to @order, notice: 'Your order has been successfully submitted.'
    else
      render :new
    end
  end

  def update
    if @order.update(order_params)
      if @order.saved_change_to_attribute? :status, to: 'approved'
        OrderMailer.approved_status_order(@order).deliver
      elsif @order.saved_change_to_attribute? :status, to: 'printing'
        OrderMailer.printing_status_order(@order).deliver
      elsif @order.saved_change_to_attribute? :status, to: 'shipped'
        OrderMailer.shipped_status_order(@order).deliver
      end         
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_url
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:invoiced, :status, :date, :entity, :user_id, :address_id, :tracking, :ship_vendor, :ship_cost, :spreadsheet_link, line_items_attributes: [:id, :league, :team, :division, :shirtcolor, :inkcolor, :shirtsize, :shirt_quantity, :order_id])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_all_orders.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>League</th>
      <th>Due Date</th>
      <th>Qty</th>
      <th>Tracking</th>
      <!-- <th>Edit</th>
      <th>Delete</th> -->
    </tr>
  </thead>

  <tbody>
    <% if current_user.role == "admin" %>
      <% Order.where(status: "shipped").each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <td>
            <% if order.ship_vendor == 'usps' %>
              <a href="https://tools.usps.com/go/TrackConfirmAction?tLabels=<%= order.tracking %>" target="_blank"><i class="fa fa-truck fa-xl" aria-hidden="true"></i> Track </a>
            <% elsif order.ship_vendor == 'ups' %>
              <a href="https://www.ups.com/track?loc=en_US&tracknum=<%= order.tracking %>&requester=WT" target="_blank"><i class="fa fa-truck fa-xl" aria-hidden="true"></i> Track </a>
            <% end %>
          </td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <% Order.where(status: "shipped", user: current_user).each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <td><%= order.tracking %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/orders/_approved_status.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>League</th>
      <th>Due Date</th>
      <th>Qty</th>
      <!-- <th>Edit</th>
      <th>Delete</th> -->
    </tr>
  </thead>

  <tbody>
    <% if current_user.role == "admin" %>
      <% Order.where(status: "approved").each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <% Order.where(status: "approved", user: current_user).each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/orders/_box_label.html.erb
<!-- Modal -->
<% if @order.line_items.exists? %>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title center" id="exampleModalLabel">Print Label for Box</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="print-box-label">
          <div class="row">
            <div class="col-md-4">
              <h6>Order #</h6><h3><%= @order.id %></h3>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4 text-right">
              <h6>Date</h6><h3><%= @order.date %></h3> 
            </div>
          </div>
          <div class="row"><br></div>
          <div class="row">
            <div class="col-md-12 center">
              <h1><%= @order.line_items.first.league %></h1>
            </div>
          </div>
          <div class="row"><br></div>
          <div class="row">
            <div class="col-md-4">
              <h6>Total Shirts</h6>
              <h3><%= @order.line_items.sum(:shirt_quantity) %></h3>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4 text-right">
              <h6>Customer</h6>
              <h3><%= @order.user.email %></h3>
            </div>
          </div>  
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" onclick="printDiv('print-box-label')">
          Print</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script>
    function printDiv(divName){
      var printContents = document.getElementById(divName).innerHTML;
      var originalContents = document.body.innerHTML;
      document.body.innerHTML = printContents;
      window.print();
      document.body.innerHTML = originalContents;
    }
  </script>

app/views/orders/_new_status.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>League</th>
      <th>Due Date</th>
      <th>Qty</th>
      <!-- <th>Edit</th>
      <th>Delete</th> -->
    </tr>
  </thead>

  <tbody>
    <% if current_user.role == "admin" %>
      <% Order.where(status: "new").each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <% Order.where(status: "new", user: current_user).each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/orders/_overview.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr class="bg-primary center">
      <th scope="col" class="center">League</th>
      <th scope="col" class="center">Team</th>
      <th scope="col" class="center">Division</th>
      <th scope="col" class="center">Shirt Color</th>
      <th scope="col" class="center">Ink Color</th>
      <th scope="col" class="center">Size</th>
      <th scope="col" class="center">Quantity</th>
      <% if current_user.role == 'admin' %>
        <th scope="col" class="center">Edit</th>
        <th scope="col" class="center">Delete</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% for line_item in @order.line_items %>
      <tr>
        <td scope="row" class="center"><%= line_item.league %></td>
        <td scope="row" class="center"><%= line_item.team %></td>
        <td scope="row" class="center"><%= line_item.division %></td>
        <td scope="row" class="center"><%= line_item.shirtcolor %></td>
        <td scope="row" class="center"><%= line_item.inkcolor %></td>
        <td scope="row" class="center"><%= line_item.shirtsize %></td>
        <td scope="row" class="center"><%= line_item.shirt_quantity %></td>
        <% if current_user.role == 'admin' %>
          <td scope="row" class="center">
            <%= link_to edit_line_item_path(line_item) do %>
              <i class="fas fa-pen-square fa-2x"></i>
            <% end %>
            </td>
          <td scope="row" class="center">
            <%= link_to line_item_path(line_item), data: {:confirm => 'Are you sure?'}, :method => :delete do %>
              <i class="fas fa-trash fa-2x"></i>
            <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/_print_total.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr class="bg-primary center">
      <th scope="col" class="center">Team</th>
      <th scope="col" class="center">Shirt Color</th>
      <th scope="col" class="center">Ink Color</th>
      <th scope="col" class="center">Quantity</th>
    </tr>
  </thead>
  <tbody>
    <% @line_items.each do |li| %>
      <tr>
        <td scope="row" class="center"><%= li[0][0] %></td>
        <td scope="row" class="center"><%= li[0][1] %></td>
        <td scope="row" class="center"><%= li[0][2] %></td>
        <td scope="row" class="center"><%= li[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/_printing_status.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>League</th>
      <th>Due Date</th>
      <th>Qty</th>
      <!-- <th>Edit</th>
      <th>Delete</th>
 -->    </tr>
  </thead>

  <tbody>
    <% if current_user.role == "admin" %>
      <% Order.where(status: "printing").each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <% Order.where(status: "printing", user: current_user).each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/orders/_shipped_status.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>League</th>
      <th>Due Date</th>
      <th>Qty</th>
      <th>Tracking</th>
      <!-- <th>Edit</th>
      <th>Delete</th> -->
    </tr>
  </thead>

  <tbody>
    <% if current_user.role == "admin" %>
      <% Order.where(status: "shipped", invoiced: false).each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <td>
            <% if order.ship_vendor == 'usps' %>
              <a href="https://tools.usps.com/go/TrackConfirmAction?tLabels=<%= order.tracking %>" target="_blank"><i class="fa fa-truck fa-xl" aria-hidden="true"></i> Track </a>
            <% elsif order.ship_vendor == 'ups' %>
              <a href="https://www.ups.com/track?loc=en_US&tracknum=<%= order.tracking %>&requester=WT" target="_blank"><i class="fa fa-truck fa-xl" aria-hidden="true"></i> Track </a>
            <% end %>
          </td>
          <td><%= order.ship_cost %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <% Order.where(status: "shipped", user: current_user).each do |order| %>
        <tr>
          <!-- <td><%= order.user.email if order.user %></td> -->
          <td><%= link_to "#{order.id}", order %></td>
          <td><%= link_to "#{order.line_items.first.league}", order if order.line_items.exists? %></td>
          <td><%= order.date %></td>
          <td><%= order.line_items.sum(:shirt_quantity) %></td>
          <td><%= order.tracking %></td>
          <% if order.user == current_user %>
            <!-- <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<% if user_signed_in? %>
  <% if @orders.where(user_id: current_user).exists? %>
    <%= link_to "Create Order", new_order_path, class: 'btn btn-primary btn-lg' %>
    <div class="">
      <div class="row">
        <div class="col-sm-6 col-md-6">
          <div class="card">
            <div class="card-header bg-primary border-success center">
              New
              <span class="badge badge-light">
                <% if current_user.role == 'admin' %>
                  <%= Order.where(status: "new").count %>
                <% else %>
                  <%= Order.where(status: "new", user: current_user).count %>
                <% end %>
              </span>
            </div>
            <div class="card-body">
              <p class="card-text">
                <%= render 'new_status' %>
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-6">
          <div class="card">
            <div class="card-header bg-success border-success center">
              Approved
              <span class="badge badge-light">
                <% if current_user.role == 'admin' %>
                  <%= Order.where(status: "approved").count %>
                <% else %>
                  <%= Order.where(status: "approved", user: current_user).count %>
                <% end %>                  
              </span>
            </div>
            <div class="card-body">
              <p class="card-text">
                <%= render 'approved_status' %>
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-6">
          <div class="card">
            <div class="card-header bg-warning border-success center">
              Printing
              <span class="badge badge-light">
                <% if current_user.role == 'admin' %>
                  <%= Order.where(status: "printing").count %>
                <% else %>
                  <%= Order.where(status: "printing", user: current_user).count %>
                <% end %>                  
              </span>
            </div>
            <div class="card-body">
              <p class="card-text"></p>
                <%= render 'printing_status' %>
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-6">
          <div class="card">
            <div class="card-header bg-info border-success center">
              Shipped
              <span class="badge badge-light">
                <% if current_user.role == 'admin' %>
                  <%= Order.where(status: "shipped").count %>
                <% else %>
                  <%= Order.where(status: "shipped", user: current_user).count %>
                <% end %>                  
              </span>
            </div>
            <div class="card-body">
              <p class="card-text"></p>
                <%= render 'shipped_status' %>
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-6">
          <div class="card">
            <div class="card-header bg-info border-success center">
              All
              <span class="badge badge-light">
                <% if current_user.role == 'admin' %>
                  <%= Order.count %>
                <% else %>
                  <%= Order.where(user: current_user).count %>
                <% end %>                  
              </span>
            </div>
            <div class="card-body">
              <p class="card-text"></p>
                <%= render 'all_orders' %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="jumbotron center">
      <%= link_to "Create an order", new_order_path, class: "btn btn-primary btn-lg" %>
    </div>
  <% end %>
<% else %>
  <div class="jumbotron center">
   <h1>Welcome to Fast Order.</h1>
   <h4>Please login to proceed.</h4>
    <p>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </p>
  </div>
<% end %>  

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<div class="row card-header">
  <div class="col-md-4"><h3>Order #<%= @order.id %></h3></div>
  <div class="col-md-7"></div>
  <div class="col-md-1">
    <% if can? :update, Order %>
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'Edit Order', edit_order_path(@order), class: 'dropdown-item' %>
          <%= link_to 'Destroy', @order, method: :destroy_all, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %>
          <%= link_to 'Box label', 'box_label', class: 'dropdown-item', data: { toggle: 'modal', target: '#exampleModal' } %> 
          <%= link_to 'spreadsheet', @order.spreadsheet_link, class: 'dropdown-item' %>
          <%= link_to "Download PDF", order_path(@order, format: :pdf), download: "#{@order.entity} - order ##{@order.id}" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% if @order.line_items.exists? %>
  <div class="row">
    <div class="card">
      <div class="row card-body">
        <div class="col-md-1"></div>
        <div class="col-md-4">
          <h5 class="card-title">Ship To:</h5>
          <p class="card-text">
            <%= @order.address.contact_name  %><br>
            <%= @order.address.street  %><br>
            <%= @order.address.unit  %>
            <%= @order.address.city  %>, <%= @order.address.state  %> <%= @order.address.zipcode  %><br>
            <%= @order.user.email %><br>
            <% if @order.ship_vendor == 'usps' %>
              <a href="https://tools.usps.com/go/TrackConfirmAction?tLabels=<%= @order.tracking %>" target="_blank"><i class="fa fa-truck fa-xl" aria-hidden="true"></i> Track </a><br>
            <% elsif @order.ship_vendor == 'ups' %>
              <a href="https://www.ups.com/track?loc=en_US&tracknum=<%= @order.tracking %>&requester=WT" target="_blank"><i class="fa fa-truck fa-xl" aria-hidden="true"></i> Track </a>
            <% end %><br>
            <% if current_user.role =='admin'  %>
              $<%= @order.ship_cost %><br>
            <% end %>
          </p>
        </div>
        <div class="col-md-4">
          <h3>Invoiced?</h3>
          <% if @order.invoiced == true %>
            <i class="fas fa-check fa-9x" style="color: green"></i>
          <% else %>
            <i class="fas fa-times fa-9x" style="color: red"></i>
          <% end %>
        </div>
        <div class="col-md-3">
          <h5 class="card-title">Details</h5>
          <p class="card-text">
            <button type="button" class="btn btn-info" style="margin-bottom: 2%;">
              Status <span class="badge badge-light"><%= @order.status.upcase %></span>
            </button><br>
            <button type="button" class="btn btn-danger" style="margin-bottom: 2%;">
              Date <span class="badge badge-light"><%= @order.date %></span>
            </button><br>
            <button type="button" class="btn btn-warning" style="margin-bottom: 2%;">
              Shirt Total <span class="badge badge-light"><%= @order.line_items.sum(:shirt_quantity) %></span>
            </button>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="card text-center">
    <div class="card-header">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true" style="color: #2c3e50;">Overview</a>
        </li>
        <% if current_user.role == 'admin' %>
          <li class="nav-item">
            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false" style="color: #2c3e50;">Print</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false" style="color: #2c3e50;">Product</a>
          </li>
        <% end %>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
          <%= render 'overview' %>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
          <%= render 'print_total' %>
        </div>
        <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
          <%= render 'order_sheet' %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="jumbotron">
    <% if current_user.role == "operator" %>
      <p class="center">Your order is currently processing. You should see approval for your order in 12 - 24 business hours.</p>
      <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated active" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
      </div>
    <% elsif current_user.role == "admin" %>
      <p class="center">Operators original spreadsheet:<br><a href="<%= @order.spreadsheet_link %>" target="_blank"><%= @order.spreadsheet_link %></a></p>
      <br><br><br>
      <%= form_tag import_line_items_path, multipart: true, class: 'center' do %>
        <%= hidden_field_tag :order_id, params[:id] %>
        <%= file_field_tag :file, style: 'margin: auto', class: 'btn btn-default btn-lg' %>
        <br>
        <%= submit_tag "Import Spreadsheet", class: 'btn btn-primary btn-lg' %>
      <% end %>
    <% end %>  
  </div>
<% end %>

<h3>Messages</h3>
<% Message.where(order_id: @order.id).each do |mess| %>
  <div class="card">
    <div class="card-header">
      <%= mess.user.email %> says...
    </div>
    <div class="card-body" style="padding: 1%;">
      <p class="card-text"><%= mess.body %></p>
      <footer class="blockquote-footer"><%= mess.created_at.strftime("%m.%d.%Y %I:%M %P") %></footer>
    </div>
  </div>
<% end %>
<%= render 'messages/form' %>

<%= render 'box_label' %>

app/views/orders/show.pdf.erb
// views/orders/show.pdf.erb

// You can include google fonts in the template.

< link href = "https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" >

// Will load pdf.css file in your assets/stylesheets dir. It will be applied to pdfs in development environment.

<%= wicked_pdf_stylesheet_link_tag "pdf" -%>

// You need to link to an outside stylesheet for production.

<%= stylesheet_link_tag "https://www.dropbox.com/s/some-link/pdf.css?raw=1" %>


// You can fill out the template with variables from the controller action.

< h3 ><%= @order.id %>< / h3 >

< h4 ><%= @order.created_at %>< / h4 >