config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :inventories
  resources :products
	resources :orders
	resources :addresses 
	resources :line_items, shallow: true do
   		collection { post :import }
   end

	devise_for :users, :controllers => { registrations: 'users/registrations' }
	
	root "pages#home"
	get "faq" => "pages#faq"
end

app/models/product.rb
class Product < ApplicationRecord
	CATEGORIES = [['hard goods', 'hard goods'], ['sec', 'sec'], ['big 10', 'big 10'], ['big 12', 'big 12'], ['pac 12', 'pac 12'], ['acc', 'acc'], ['ivy', 'ivy'], ['nfl', 'nfl'], ['popular non-power 5', 'popular non-power 5']]
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image_url, :product_category)
    end
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
	  <%= f.input :name %>
  </div>
  <div class="form-inputs">
	  <%= f.input :product_category, as: :select, collection: Product::CATEGORIES %>
  </div>
  <p>Hint: After you copy the public Dropbox link to your clipboard, just change ?dl=0 to ?raw=1 at the end of the URL.</p>
  <div class="form-inputs">
	  <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/_product_nav.html.erb
<div class="jumbotron" style="padding: 1%; position: fixed;">
  <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <a class="nav-link" id="v-pills-acc-tab" data-toggle="pill" href="#v-pills-acc" role="tab" aria-controls="v-pills-acc" aria-selected="true">ACC</a>
    <div class="dropdown-divider" style="background-color: white !important;"></div>
    <a class="nav-link" id="v-pills-big10-tab" data-toggle="pill" href="#v-pills-big10" role="tab" aria-controls="v-pills-big10" aria-selected="false">BIG 10</a>
    <div class="dropdown-divider" style="background-color: white !important;"></div>
    <a class="nav-link" id="v-pills-big12-tab" data-toggle="pill" href="#v-pills-big12" role="tab" aria-controls="v-pills-big12" aria-selected="false">BIG 12</a>
    <div class="dropdown-divider" style="background-color: white !important;"></div>
    <a class="nav-link" id="v-pills-nfl-tab" data-toggle="pill" href="#v-pills-nfl" role="tab" aria-controls="v-pills-nfl" aria-selected="false">NFL</a>
    <div class="dropdown-divider" style="background-color: white !important;"></div>
    <a class="nav-link" id="v-pills-other-tab" data-toggle="pill" href="#v-pills-other" role="tab" aria-controls="v-pills-other" aria-selected="false">Popular Non-Power 5</a>
    <div class="dropdown-divider" style="background-color: white !important;"></div>
    <a class="nav-link" id="v-pills-pac12-tab" data-toggle="pill" href="#v-pills-pac12" role="tab" aria-controls="v-pills-pac12" aria-selected="false">PAC 12</a>
    <div class="dropdown-divider" style="background-color: white !important;"></div>
    <a class="nav-link" id="v-pills-sec-tab" data-toggle="pill" href="#v-pills-sec" role="tab" aria-controls="v-pills-sec" aria-selected="false">SEC</a>
    <div class="dropdown-divider" style="background-color: white !important;"></div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <%= render 'product_nav' %>
  </div>
  <div class="col-md-9">
    <div class="tab-content" id="v-pills-tabContent">
      <div class="row tab-pane fade in active" id="v-pills-acc" role="tabpanel" aria-labelledby="v-pills-acc-tab">
        <% @products.where(product_category: 'acc').each_slice(4) do |products| %>
          <div class="row">
            <% products.each do |p| %>
              <div class="col-md-3">
                <img class="card-img-top" src="<%= p.image_url %>" alt="<%= p.name %>" style="width: 100%;">
                <div class="card-body">
                  <b><p class="card-title center"><%= p.name.upcase %></p></b>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="v-pills-big10" role="tabpanel" aria-labelledby="v-pills-big10-tab">
        <% @products.where(product_category: 'big10').each_slice(4) do |products| %>
          <div class="row">
            <% products.each do |p| %>
              <div class="col-md-3">
                <img class="card-img-top" src="<%= p.image_url %>" alt="<%= p.name %>" style="width: 100%;">
                <div class="card-body">
                  <b><p class="card-title center"><%= p.name.upcase %></p></b>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="v-pills-big12" role="tabpanel" aria-labelledby="v-pills-big12-tab">
        <% @products.where(product_category: 'big12').each_slice(4) do |products| %>
          <div class="row">
            <% products.each do |p| %>
              <div class="col-md-3">
                <img class="card-img-top" src="<%= p.image_url %>" alt="<%= p.name %>" style="width: 100%;">
                <div class="card-body">
                  <b><p class="card-title center"><%= p.name.upcase %></p></b>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="v-pills-nfl" role="tabpanel" aria-labelledby="v-pills-nfl-tab">
        <% @products.where(product_category: 'nfl').each_slice(4) do |products| %>
          <div class="row">
            <% products.each do |p| %>
              <div class="col-md-3">
                <img class="card-img-top" src="<%= p.image_url %>" alt="<%= p.name %>" style="width: 100%;">
                <div class="card-body">
                  <b><p class="card-title center"><%= p.name.upcase %></p></b>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="v-pills-other" role="tabpanel" aria-labelledby="v-pills-other-tab">
        <% @products.where(product_category: 'other').each_slice(4) do |products| %>
          <div class="row">
            <% products.each do |p| %>
              <div class="col-md-3">
                <img class="card-img-top" src="<%= p.image_url %>" alt="<%= p.name %>" style="width: 100%;">
                <div class="card-body">
                  <b><p class="card-title center"><%= p.name.upcase %></p></b>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="v-pills-pac12" role="tabpanel" aria-labelledby="v-pills-pac12-tab">
        <% @products.where(product_category: 'pac12').each_slice(4) do |products| %>
          <div class="row">
            <% products.each do |p| %>
              <div class="col-md-3">
                <img class="card-img-top" src="<%= p.image_url %>" alt="<%= p.name %>" style="width: 100%;">
                <div class="card-body">
                  <b><p class="card-title center"><%= p.name.upcase %></p></b>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="v-pills-sec" role="tabpanel" aria-labelledby="v-pills-sec-tab">
        <% @products.where(product_category: 'sec').each_slice(4) do |products| %>
          <div class="row">
            <% products.each do |p| %>
              <div class="col-md-3">
                <img class="card-img-top" src="<%= p.image_url %>" alt="<%= p.name %>" style="width: 100%;">
                <div class="card-body">
                  <b><p class="card-title center"><%= p.name.upcase %></p></b>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= @product.name %>
<%= @product.product_category %>
<%= @product.size %>
<img src="<%= @product.image_url %>">


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>