config/routes.rb
Rails.application.routes.draw do

  resources :messages
  resources :inventories
  resources :products
	resources :orders
	resources :addresses 
	resources :line_items, shallow: true do
   		collection { post :import }
   end

	devise_for :users, :controllers => { registrations: 'users/registrations' }
	
	root "pages#home"
	get "faq" => "pages#faq"
end

app/views/layouts/_header.html.erb
<nav class="navbar fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="col-md-2 navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Fast Order", root_path, class: "navbar-brand center" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>          
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul> 
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_side_nav.html.erb
<% if user_signed_in? %>
	<nav class="col-md-2 sidebar">
	  <div class="">
	    <ul class="nav">
	      <li class="nav-item">
	      	<%= link_to "Dashboard", orders_path, class: 'nav-link' %>
	      </li>
	      <div class="dropdown-divider"></div>
	      <li class="nav-item">
	      	<%= link_to "Orders", orders_path, class: 'nav-link' %>
	      </li>
	      <div class="dropdown-divider"></div>
	      <li class="nav-item">
	      	<%= link_to "New Order", new_order_path, class: 'nav-link' %>
	      </li>
	      <div class="dropdown-divider"></div>
	      <li class="nav-item">
	         <%= link_to "Visuals", products_path, class: 'nav-link' %>
	      </li>
	      <div class="dropdown-divider"></div>
	      <% if current_user.role == 'admin' %>
            <li><%= link_to "Analytics", line_items_path, class: 'nav-link' %></li>
            <div class="dropdown-divider"></div>
            <li><%= link_to "Inventory", inventories_path, class: 'nav-link' %></li>
            <div class="dropdown-divider"></div>
          <% end %>
          <li><%= link_to "Account Settings", edit_user_registration_path, class: 'nav-link' %></li>
          <div class="dropdown-divider"></div>
	    </ul>
	  </div>
	</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FastOrder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
    <div class="container-fluid">
      <% if user_signed_in? %>
        <div class="row">
          <%= render 'layouts/side_nav' %>
          <div class="col-md-2"></div>
          <div class="col-md-10">
            <br>
            <%= yield %>
          </div>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>